get in improvements from dgoss
Signed-off-by: Felix Bartels <felix@host-consultants.de>

diff --git a/extras/dgoss/dcgoss b/extras/dgoss/dcgoss
--- a/extras/dgoss/dcgoss
+++ b/extras/dgoss/dcgoss
@@ -5,8 +5,13 @@ set -e
 USAGE="USAGE: $(basename "$0") [run|edit] <docker-compose-service>"
 GOSS_FILES_PATH="${GOSS_FILES_PATH:-.}"
 
-info() { echo -e "INFO: $*"; }
-error() { echo -e "ERROR: $*";exit 1; }
+info() {
+    echo -e "INFO: $*" >&2;
+}
+error() {
+    echo -e "ERROR: $*" >&2;
+    exit 1;
+}
 
 cleanup() {
     set +e
@@ -83,6 +88,10 @@ case "$1" in
             fi
         fi
         [[ $GOSS_SLEEP ]] && { info "Sleeping for $GOSS_SLEEP"; sleep "$GOSS_SLEEP"; }
+        info "Container health"
+        if ! docker top $service; then
+            docker logs $service
+        fi
         info "Running Tests"
         if [[ -z "${GOSS_VARS}" ]]; then
             docker exec "$service" sh -c "/goss/goss -g /goss/goss.yaml render | /goss/goss -g - validate $GOSS_OPTS"
