shellcheck fixes
Signed-off-by: Felix Bartels <felix@host-consultants.de>

diff --git a/extras/dgoss/dcgoss b/extras/dgoss/dcgoss
--- a/extras/dgoss/dcgoss
+++ b/extras/dgoss/dcgoss
@@ -17,7 +17,7 @@ cleanup() {
     set +e
     { kill "$log_pid" && wait "$log_pid"; } 2> /dev/null
     rm -rf "$tmp_dir"
-    if [[ ! -z $service ]]; then
+    if [[ -n "$service" ]]; then
         info "Deleting container"
         docker-compose down -v > /dev/null
     fi
@@ -29,12 +29,12 @@ run(){
     chmod 755 "$tmp_dir/goss"
     [[ -e "${GOSS_FILES_PATH}/goss.yaml" ]] && cp "${GOSS_FILES_PATH}/goss.yaml" "$tmp_dir"
     [[ -e "${GOSS_FILES_PATH}/goss_wait.yaml" ]] && cp "${GOSS_FILES_PATH}/goss_wait.yaml" "$tmp_dir"
-    [[ ! -z "${GOSS_VARS}" ]] && [[ -e "${GOSS_FILES_PATH}/${GOSS_VARS}" ]] && cp "${GOSS_FILES_PATH}/${GOSS_VARS}" "$tmp_dir"
+    [[ -n "${GOSS_VARS}" ]] && [[ -e "${GOSS_FILES_PATH}/${GOSS_VARS}" ]] && cp "${GOSS_FILES_PATH}/${GOSS_VARS}" "$tmp_dir"
 
     info "Starting docker container"
-    docker-compose run -d -T --name $service -v "$tmp_dir:/goss" $service
-    docker logs -f $service > "$tmp_dir/docker_output.log" 2>&1 &
-    log_pid=$!
+    docker-compose run -d -T --name "$service" -v "$tmp_dir:/goss" "$service"
+    docker logs -f "$service" > "$tmp_dir/docker_output.log" 2>&1 &
+    log_pid="$!"
     info "Container name: $service"
 }
 
@@ -51,26 +51,27 @@ get_docker_file() {
 # Main
 tmp_dir=$(mktemp -d /tmp/tmp.XXXXXXXXXX)
 chmod 777 "$tmp_dir"
-trap 'ret=$?;cleanup;exit $ret' EXIT
-service=$2
+# shellcheck disable=SC2154
+trap 'ret=$?; cleanup; exit $ret' EXIT
+service="$2"
 
 if [[ ! -f docker-compose.yaml && ! -f docker-compose.yml ]]; then
     echo "no docker-compose file found in ."
     exit 1
 fi
 
-state=$(docker inspect --format '{{.State.Status}}' $service 2> /dev/null || true)
-if [[ $state == running ]]; then
-    docker rm -f $service
-elif [[ $state == exited ]]; then
-    docker rm $service
+state=$(docker inspect --format '{{.State.Status}}' "$service" 2> /dev/null || true)
+if [[ "$state" == running ]]; then
+    docker rm -f "$service"
+elif [[ "$state" == exited ]]; then
+    docker rm "$service"
 fi
 
-GOSS_PATH="${GOSS_PATH:-$(which goss 2> /dev/null || true)}"
-[[ $GOSS_PATH ]] || { error "Couldn't find goss installation, please set GOSS_PATH to it"; }
-[[ ${GOSS_OPTS+x} ]] || GOSS_OPTS="--color --format documentation"
-[[ ${GOSS_WAIT_OPTS+x} ]] || GOSS_WAIT_OPTS="-r 30s -s 1s > /dev/null"
-GOSS_SLEEP=${GOSS_SLEEP:-0.2}
+GOSS_PATH="${GOSS_PATH:-$(command -v goss 2> /dev/null || true)}"
+[[ "$GOSS_PATH" ]] || { error "Couldn't find goss installation, please set GOSS_PATH to it"; }
+[[ "${GOSS_OPTS+x}" ]] || GOSS_OPTS="--color --format documentation"
+[[ "${GOSS_WAIT_OPTS+x}" ]] || GOSS_WAIT_OPTS="-r 30s -s 1s > /dev/null"
+GOSS_SLEEP="${GOSS_SLEEP:-0.2}"
 
 case "$1" in
     run)
@@ -87,10 +88,10 @@ case "$1" in
                 fi
             fi
         fi
-        [[ $GOSS_SLEEP ]] && { info "Sleeping for $GOSS_SLEEP"; sleep "$GOSS_SLEEP"; }
+        [[ "$GOSS_SLEEP" ]] && { info "Sleeping for $GOSS_SLEEP"; sleep "$GOSS_SLEEP"; }
         info "Container health"
-        if ! docker top $service; then
-            docker logs $service
+        if ! docker top "$service"; then
+            docker logs "$service"
         fi
         info "Running Tests"
         if [[ -z "${GOSS_VARS}" ]]; then
@@ -105,7 +106,7 @@ case "$1" in
         docker exec -it "$service" sh -c 'cd /goss; PATH="/goss:$PATH" exec sh'
         get_docker_file "/goss/goss.yaml"
         get_docker_file "/goss/goss_wait.yaml"
-        [[ ! -z "${GOSS_VARS}" ]] && get_docker_file "/goss/${GOSS_VARS}"
+        [[ -n "${GOSS_VARS}" ]] && get_docker_file "/goss/${GOSS_VARS}"
         ;;
     *)
         error "$USAGE"
